### ISSUE TITLE
OldPlanette blogposts

### ISSUE THREAD

**Issue by f3l1x** [contributte/planette-site#2]
I suggest to include them to the mainstream. Ok?

**Comment by paveljanda** [comment]
Yes. But how is it related to "blogpost"/"blog"? Isn't it more of a cookbook then a blog?

**Comment by f3l1x** [comment]
Well, you're right. We can introduce new category **cookbook** for small tips, tricks, etc? :+1:

**Comment by paveljanda** [comment]
First we should define what means `coocbook`, `article`, `blog`, `blogpost`, `tip`, etc in context of Planette. :D

By cookbook I understand a **place, where are aggregated all articles and tips about nette (of course also using doctrine, redis, es, dibi, .....) but classified under different categories (quickstart, blog in 20 minutes, sessions, etc)**.

@f3l1x What do you understand under term "cookbook"?

**Comment by f3l1x** [comment]
We have to consider what **Hugo** can do and what can't.

There's the **type** for each markdown, it says what kind of page is it. This type has own layout/theme/design whatever.

I would like to have types as little as possible.

Blogpost, blog, article, cookbook and tip is in our & Hugo's terminology **blog**. I am working on design for type blog.

```
[taxonomies]
tag = "tags"
category = "categories"
```

Let's take a look on taxonomies at Hugo docs: https://gohugo.io/taxonomies/usage/

So, we have a **type**. 

Otherwise, **cookbook** is for me category. Same for tip and others. We could list all blogposts in category **cookbook** on special cookbook page. ;-)

Do you agree? :-)

**Comment by paveljanda** [comment]
Thanks for explaining to me.
That does make sense.

But I would expect more categories in `cookbook` category. :D That, I suppose, is not possible with Hugo. Or we can have one repo for cookbook, another one for blog (like really a blog :D), another for homepage and another repos for another types of content.

Wait, what is `series`?

**Comment by f3l1x** [comment]
Closing it in favor of #1.
