### ISSUE TITLE
2015-07-24: dependency-injection-decorator

### ISSUE THREAD

**Issue by paveljanda** [contributte/planette-site#51]
decorator:
        App\Presenters\BasePresenter:
            setup:
                - setParameter(%parameter%)

**Comment by paveljanda** [comment]
author: Northys (jiri.travnicek@outlook.com)

**Comment by paveljanda** [comment]
I hope northys won't be said about it... I took credit for the topic and wrote a short article about decorator.

**Comment by f3l1x** [comment]
I think it's cool ;-)
