### ISSUE TITLE
2015-07-27: nasazeni-acl-vrstvy

### ISSUE THREAD

**Issue by paveljanda** [contributte/planette-site#52]
Začneme stažením git repozitáře: `composer create-project nette/web-project mujweb`.

Je hezké, že se můžeme uživatele ptát, jestli má tu a tu roli, nebo jestli je vůbec přihlášený.

```php
<?php

namespace App\Presenters;

use Nette;

class HomepagePresenter extends Nette\Application\UI\Presenter
{

        public function actionDefault()
        {
                dump($this->user->isLoggedIn());
        dump($this->user->isInRole('admin'));

        die;
        }

}
```

Ale pokud bychom měli tímto stylem postavit celou velkou aplikaci, brzy bychom skončili, jak by to začalo být nepřehledné.
Nette poskytuje (jak jinak) velice příjemnou třídu pro práci se složitějším ACL. Jmenuje se `Permission`. Zkusíme si tedy postavit jednu takovou třídu, která bude s `Nette\Security\Permission` pracovat.

```php
<?php

namespace App\Security;

use Nette,
    Nette\Security\Permission;

class AuthorizatorFactory extends Nette\Object
{

    const ROLE_GUEST = 'guest';
    const ROLE_USER = 'user';


    public function create()
    {
        $acl = new Permission;

        /**
         * Roles 1*
         */
        $acl->addRole(self::ROLE_GUEST);
        $acl->addRole(self::ROLE_USER, self::ROLE_GUEST); // 2*

        /**
         * Resoures 3*
         */
        $acl->addResource('Front');
        $acl->addResource('Front:Homepage', 'Front');
        $acl->addResource('Front:About', 'Front');

        $acl->addResource('User');
        $acl->addResource('User:Sign', 'User');
        $acl->addResource('User:Profile', 'User');


        /**
         * Permissions 4*
         */
        $acl->allow(self::ROLE_GUEST, 'Front');
        $acl->allow(self::ROLE_GUEST, 'User:Sign');

        $acl->allow(self::ROLE_USER,  Permission::ALL, Permission::ALL);

        return $acl;
    }

}
```

Popišme si, co jsme to vyrobili:
1) Vytvořii jsme si 2 role uživatele (`guest` - to je automaticky nepřihlášený uživatel a `user`)
2) Role `user` automaticky dědí všechny práva od `guest`
3) Vytvořili jsme 2 kořenové zdroje - resources: "Front" a "User". Potom další, která jsou odvozená od těchto kořenových.
4) Roli `guest` jsme dovolili koukat na vše, co dědí od zdroje "Front" plus "User:Sign", aby se mohl přihlásit. Roli `user` jsme dovolili všechno na světě.

Taková třída je sice hezká, ale taky bychom ji měli zapojit do práce. Přidáme do configu toto:

```php
services:
        ...
        - App\Security\AuthorizatorFactory
        -
                class: Nette\Security\Permission
                factory: @App\Security\AuthorizatorFactory::create
```

Zkusíme nové ACL v praxi:

```php
namespace App\Presenters;

use Nette;

class HomepagePresenter extends Nette\Application\UI\Presenter
{

        public function actionDefault()
        {
                dump($this->user->isAllowed('Front:Homepage')); // => TRUE
                dump($this->user->isAllowed('User'));           // => FALSE
        dump($this->user->isAllowed('User:Sign'));      // => TRUE

        die;
        }

}
```

To by bylo. Teď musíme zautomatizovat proces ověřování role uživatele někde v `BasePresenteru` (**od kterého budou ostatní presentery dědit**), abychom nemuseli v každé akci každého presenteru volat `$this->user->isAllowed('...')`.
Vytvoříme dva další Presentery: AboutPresenter a UserPresenter. Všem 3 presenterům (včetně HomepagePresenteru) řekneme anotací, že se jedná o ten a ten resource.
**Pozor!** Určení zdrojů presenteru pomocí anotací je pouze jeden z mnoha způsobů, jak docílit kýženého efektu. Pokud si vymyslíte jiný, směle do toho.

Tedy nejprve `BasePresenter`:

```php
namespace App\Presenters;

use Nette;

class BasePresenter extends Nette\Application\UI\Presenter
{

}
```

A ostatní presentery:

```php
namespace App\Presenters;

/**
 * @resource Front:Homepage
 */
class HomepagePresenter extends BasePresenter
{

}
```

```php
namespace App\Presenters;

/**
 * @resource Front:About
 */
class AboutPresenter extends BasePresenter
{

}
```

```php
namespace App\Presenters;

/**
 * @resource User:Profile
 */
class ProfilePresenter extends BasePresenter
{

}
```

V SignPresenteru ještě stihneme vytvořit přihlašovací formulář, kratičkou validaci formuláře a Sign:in/out metodu:

```php
namespace App\Presenters;

use Nette,
        App\Security\AuthorizatorFactory;

/**
 * @resource User:Sign
 */
class SignPresenter extends BasePresenter
{

        public function actionIn()
        {
                if ($this->user->isLoggedIn()) {
                        $this->redirect('Profile:');
                }
        }


        public function actionOut()
        {
                $this->user->logout();
                $this->flashMessage('Byli jste odhlášeni.');
                $this->redirect('in');
        }


        public function createComponentSignInForm()
        {
                $form = new Nette\Application\UI\Form;

                $form->addText('username', 'Username:');
                $form->addPassword('password', 'Password:');
                $form->addSubmit('submit', 'Submit');

                $form->onValidate[] = [$this, 'validateCreditians'];
                $form->onSuccess[] = [$this, 'signInFormSucceeded'];

                return $form;
        }


        public function validateCreditians($form, $values)
        {
                if ($values->username !== 'franta' || $values->password !== 'heslo') {
                        $form->addError('Nesprávné přihlašovací údaje');
                }
        }


        public function signInFormSucceeded($form, $values)
        {
                $data = ['username' => $values->username];
                $identity = new Nette\Security\Identity(1, AuthorizatorFactory::ROLE_USER, $data);

                $this->user->login($identity);
                $this->redirect('Profile:');
        }

}
```

A nesmíme zapomenou malinkou šablonku, kam umístíme přihlašovací formulář. Soubor `app/presenters/templates/Sing/in`:

```php
{block content}
        {control signInForm}
{/block}
```

To bychom měli. Stále ještě někam potřebujeme umístit kontrolu, která se bude spouštět při **každém** requestu aplikace. `Nette\Application\UI\Presenter` již má metodu pro to určenou. Jmenuje se `checkRequirements`. Přepíšeme ji v našem `BasePresenteru`:

```php
namespace App\Presenters;

use Nette;

class BasePresenter extends Nette\Application\UI\Presenter
{

        /**
         * Check authorization
         * @return void
         */
        public function checkRequirements($element)
        {
                if ($element instanceof Nette\Reflection\Method) {
                        /**
                         * Check permissions for Action/handle methods
                         *
                         *  - Do not that (rely on presenter authorization)
                         */
                        return;
                } else {
                        /**
                         * Check permissions for presenter access
                         */
                        $resource = $element->getAnnotation('resource'); // 1*
                }

                if (!$this->user->isAllowed($resource)) { // 2*
                        if (!$this->user->isLoggedIn()) {
                                $this->redirect('Sign:in', ['backlink' => $this->storeRequest()]);
                        } else {
                                throw new Nette\Application\ForbiddenRequestException;
                        }
                }
        }

}
```

Tato metoda se volá **dvakrát**. Jednou pro Presenter, podruhé pro konkrétní akci. Tedy pokud otevřu URL `/sign/in`, zavolá se metoda nejprve s reflexí SignPresenteru jako argumentem a podruhé s argumentem reflexí metody `actionIn`.
My si budeme kontrolovat práva přístupu pouze v jednom ze spuštění - v tom prvním:
1) Zjistíme hodnotu anotace `@resource` presenteru a
2) Zkusíme, zda do tohoto resource má uživatel přístup. Pokud ano, nic neděláme - pustíme ho dál. Pokud tam nesmí, tak:
        - V případě, že je přihlášený, oznámíme mu, že tam nemá přístup [kód 403]
    - V opačném případě ho přesměrujeme na přihlašovácí stránku

Přejděme nyní na URL homepage `/`. Tam může každý. Nyní zkusíme `/profile`. A hele, tam nemůžeme, aplikace nás přesměruje na `/sign/in`. Po přihlášení nás opět aplikace sama (!!) přesměruje na původní URL `/profile`. Proč, to najdete v dokumentaci (https://pla.nette.org/cs/jak-po-odeslani-formulare-zobrazit-stejnou-stranku). Ještě na nás ale bafne Tracy, že neexistuje šablona profilu. Tu už si zvládnete vytvořit podle sebe.

A tak, no.

--------

**Krok 2**

Takto jednoduchou implementaci ACL můžeme libovolně rozšiřovat, například:
1) Můžeme uživatelským rolím definovat ještě výčet "privileges": `$this->allow(self::ROLE_GUEST, 'Front', ['read', 'write]);` a tyto privileges kontrolovat skrze anotace akcí presenteru (tentokrát v první podmínce IFu metody `checkRequirments`).
2) Zajistit si dědičnost anotace presenterů (vhodné pro modulární aplikaci).
3) Protkat aplikaci dynamickou ACL vrstvou.
4) ...

**Comment by paveljanda** [comment]
author: Pavel Janda (ret.pvljanda@gmail.com)

**Comment by paveljanda** [comment]
@f3l1x Do you think it is possible for you to take a short look on the translated article?
 https://github.com/planette/planette/commit/f53543e6e9e6c2efc0a7a2ba3b95b00fad19728e
Just if it makes sense etc.. It is quite a long text. Thanks a lot!

**Comment by f3l1x** [comment]
Sure, I'm going to check it.
